### ISSUE TITLE
老的新闻图片无法显示

### ISSUE THREAD

**Issue by yanyin1986** [MuShare/EasyJapanese#18]
杭州的测试同学报告说，5月下面的新闻都没有缩略图了。
理论上是5月的新闻应该有图片的，所以要排查一下。

![161563926601_ pic](https://user-images.githubusercontent.com/1109143/61755336-1820bb80-adf2-11e9-956e-2b97a915c65e.jpg)

**Comment by yanyin1986** [comment]
<img src='https://user-images.githubusercontent.com/1109143/61755582-4a7ee880-adf3-11e9-81a8-616e75eb4400.png' width=320>
<img src='https://user-images.githubusercontent.com/1109143/61755648-8154fe80-adf3-11e9-95db-dc6ed36ae2fd.PNG' width=320>

网页版可以显示的图片，客户端无法显示。

**Comment by lm2343635** [comment]
😂

**Comment by yanyin1986** [comment]
应该是客户端的问题，我来搞定。
